# Generated by Django 3.2.14 on 2022-07-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0002_simulationdatapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='equation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
