# Generated by Django 3.2.14 on 2022-07-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0003_element_equation'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationdatapoint',
            name='scenario',
            field=models.CharField(default='default_scenario', max_length=200),
            preserve_default=False,
        ),
    ]
