# Generated by Django 3.2.14 on 2022-07-15 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0005_element_sim_input_var'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimulationDataPoint',
            new_name='SimulatedDataPoint',
        ),
        migrations.AddField(
            model_name='element',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InterpolatedDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpolateddatapoints', to='sahel.element')),
            ],
        ),
    ]
