# Generated by Django 3.2.14 on 2022-07-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0006_auto_20220715_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measureddatapoints', to='sahel.element')),
            ],
        ),
        migrations.DeleteModel(
            name='InterpolatedDataPoint',
        ),
    ]
