# Generated by Django 3.2.14 on 2022-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0007_auto_20220715_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='sd_type',
            field=models.CharField(blank=True, choices=[('Stock', 'Stock'), ('Flow', 'Flow'), ('Variable', 'Variable')], max_length=100, null=True),
        ),
    ]
