# Generated by Django 3.2.14 on 2022-07-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0009_alter_element_equation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='equation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
