# Generated by Django 3.2.14 on 2022-07-15 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0010_alter_element_equation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('from_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_connections', to='sahel.element')),
                ('to_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_connections', to='sahel.element')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
