# Generated by Django 3.2.14 on 2022-07-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0011_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='sd_sink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inflows', to='sahel.element'),
        ),
        migrations.AddField(
            model_name='element',
            name='sd_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outflows', to='sahel.element'),
        ),
    ]
