# Generated by Django 3.2.14 on 2022-07-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0012_auto_20220715_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='sd_stock_initial_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
