# Generated by Django 3.2.14 on 2022-07-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0013_element_sd_stock_initial_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='sd_stock_initial_value',
        ),
    ]
