# Generated by Django 3.2.14 on 2022-07-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0014_remove_element_sd_stock_initial_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('from_element', 'to_element')},
        ),
    ]
