# Generated by Django 3.2.14 on 2022-07-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0015_alter_connection_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulateddatapoint',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
