# Generated by Django 3.2.14 on 2022-07-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0017_auto_20220719_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='RegularDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_date', models.DateTimeField()),
                ('hdx_identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('hdx_resource_number', models.IntegerField(blank=True, null=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regulardataset', to='sahel.source')),
            ],
        ),
    ]
