# Generated by Django 3.2.14 on 2022-07-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0018_regulardataset_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='measureddatapoint',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measureddatapoints', to='sahel.source'),
        ),
    ]
