# Generated by Django 3.2.14 on 2022-07-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0019_measureddatapoint_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measureddatapoint',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
