# Generated by Django 3.2.14 on 2022-07-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0020_alter_measureddatapoint_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='vam_commodity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
