# Generated by Django 3.2.14 on 2022-07-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0021_element_vam_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='measureddatapoint',
            name='admin1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='measureddatapoint',
            name='admin2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='measureddatapoint',
            name='market',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='simulateddatapoint',
            name='admin1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='simulateddatapoint',
            name='admin2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
