# Generated by Django 3.2.14 on 2022-07-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0022_auto_20220720_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='high_is_bad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='element',
            name='high_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='mid_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
