# Generated by Django 3.2.14 on 2022-07-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0023_auto_20220722_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='sd_type',
            field=models.CharField(blank=True, choices=[('Stock', 'Stock'), ('Flow', 'Flow'), ('Variable', 'Variable'), ('Input', 'Input'), ('Constant', 'Constant')], max_length=100, null=True),
        ),
    ]
