# Generated by Django 3.2.14 on 2022-07-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0024_alter_element_sd_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='unit',
            field=models.CharField(blank=True, choices=[('tête', 'tête'), ('tête / mois', 'tête / mois'), ('FCFA', 'FCFA'), ('FCFA / mois', 'FCFA / mois'), ('FCFA / jour', 'FCFA / jour'), ('kg', 'kg'), ('kg / mois', 'kg / mois'), ('kg / jour', 'kg / jour'), ('kcal', 'kcal'), ('kcal / jour', 'kcal / jour'), ('1', '1')], max_length=100, null=True),
        ),
    ]
