# Generated by Django 3.2.14 on 2022-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0026_alter_element_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='unit',
            field=models.CharField(blank=True, choices=[('tête', 'tête'), ('tête / mois', 'tête / mois'), ('FCFA', 'FCFA'), ('FCFA / mois', 'FCFA / mois'), ('FCFA / jour', 'FCFA / jour'), ('FCFA / tête', 'FCFA / tête'), ('FCFA / kg', 'FCFA / kg'), ('FCFA / L', 'FCFA / L'), ('kg', 'kg'), ('kg / mois', 'kg / mois'), ('kg / jour', 'kg / jour'), ('L', 'L'), ('L / mois', 'L / mois'), ('L / jour', 'L / jour'), ('kcal', 'kcal'), ('kcal / jour', 'kcal / jour'), ('1', '1')], max_length=100, null=True),
        ),
    ]
