# Generated by Django 3.2.14 on 2022-07-26 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0027_alter_element_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ConstantValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantvalues', to='sahel.element')),
                ('response_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantvalues', to='sahel.responseoption')),
            ],
        ),
    ]
