# Generated by Django 3.2.14 on 2022-07-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0028_constantvalue_responseoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulateddatapoint',
            name='responseoption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulateddatapoints', to='sahel.responseoption'),
        ),
    ]
