# Generated by Django 3.2.14 on 2022-07-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0029_simulateddatapoint_responseoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='constant_default_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
