# Generated by Django 3.2.14 on 2022-07-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0030_element_constant_default_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constantvalue',
            old_name='response_option',
            new_name='responseoption',
        ),
    ]
