# Generated by Django 3.2.14 on 2022-07-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0031_rename_response_option_constantvalue_responseoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulateddatapoint',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulateddatapoints', to='sahel.element'),
        ),
    ]
