# Generated by Django 3.2.14 on 2022-07-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0033_alter_element_sd_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalInputDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonalinputdatapoints', to='sahel.element')),
            ],
        ),
    ]
