# Generated by Django 3.2.14 on 2022-07-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0034_seasonalinputdatapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='constant_default_value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
