# Generated by Django 3.2.14 on 2022-07-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0035_alter_element_constant_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='aggregate_by',
            field=models.CharField(choices=[('MEAN', 'MEAN'), ('SUM', 'SUM')], default='MEAN', max_length=200),
        ),
    ]
