# Generated by Django 3.2.14 on 2022-07-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0036_element_aggregate_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='dm_globalform_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='dm_globalform_field_badvalue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='dm_globalform_field_good',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='dm_globalform_field_goodvalue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='dm_globalform_field_ok',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='dm_globalform_field_okvalue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='dm_globalform_fieldgroup',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
