# Generated by Django 3.2.14 on 2022-08-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0037_auto_20220729_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='dm_globalform_field_goodvalue',
            new_name='dm_globalform_field_highvalue',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='dm_globalform_field_badvalue',
            new_name='dm_globalform_field_lowvalue',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='dm_globalform_field_okvalue',
            new_name='dm_globalform_field_midvalue',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='dm_globalform_field_good',
            new_name='dm_globalform_group_highfield',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='dm_globalform_field_ok',
            new_name='dm_globalform_group_midfield',
        ),
        migrations.AddField(
            model_name='element',
            name='dm_globalform_group_lowfield',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
