# Generated by Django 3.2.14 on 2022-08-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0038_auto_20220801_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastedDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasteddatapoints', to='sahel.element')),
            ],
        ),
    ]
