# Generated by Django 3.2.14 on 2022-08-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0039_forecasteddatapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='source_for_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_element_uses', to='sahel.source'),
        ),
        migrations.AddField(
            model_name='forecasteddatapoint',
            name='admin1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forecasteddatapoint',
            name='admin2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
