# Generated by Django 3.2.14 on 2022-08-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0041_source_number_of_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='sd_type',
            field=models.CharField(blank=True, choices=[('Stock', 'Stock'), ('Flow', 'Flow'), ('Variable', 'Variable'), ('Input', 'Input'), ('Constant', 'Constant'), ('Seasonal Input', 'Entrée Saisonnière'), ('Pulse Input', 'Entrée Impulsion')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PulseValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulsevalues', to='sahel.element')),
                ('responseoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulsevalues', to='sahel.responseoption')),
            ],
        ),
    ]
