# Generated by Django 3.2.14 on 2022-08-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0042_auto_20220802_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulsevalue',
            old_name='height',
            new_name='value',
        ),
    ]
