# Generated by Django 3.2.14 on 2022-08-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0043_rename_height_pulsevalue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsevalue',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
