# Generated by Django 3.2.14 on 2022-08-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0047_alter_element_sd_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='sd_type',
            field=models.CharField(blank=True, choices=[('Stock', 'Stock'), ('Flow', 'Flow'), ('Variable', 'Variable'), ('Input', 'Input'), ('Constant', 'Constant'), ('Seasonal Input', 'Entrée Saisonnière'), ('Pulse Input', 'Entrée Impulsion'), ('Household Constant', 'Qualité Ménage')], max_length=100, null=True),
        ),
    ]
