# Generated by Django 3.2.14 on 2022-08-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0051_alter_element_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
