# Generated by Django 3.2.14 on 2022-08-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0054_alter_element_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='simulateddatapoint',
            old_name='scenario',
            new_name='old_scenario',
        ),
        migrations.AlterField(
            model_name='element',
            name='sd_type',
            field=models.CharField(blank=True, choices=[('Stock', 'Stock'), ('Flow', 'Flow'), ('Variable', 'Variable'), ('Input', 'Input'), ('Constant', 'Constant'), ('Seasonal Input', 'Entrée Saisonnière'), ('Pulse Input', 'Entrée Impulsion'), ('Household Constant', 'Qualité Ménage'), ('Scenario Constant', 'Variation Scénario')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ScenarioConstantValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarioconstantvalues', to='sahel.element')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarioconstantvalues', to='sahel.scenario')),
            ],
        ),
    ]
