# Generated by Django 3.2.14 on 2022-08-14 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0055_auto_20220814_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulateddatapoint',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulateddatapoints', to='sahel.scenario'),
        ),
    ]
