# Generated by Django 3.2.14 on 2022-08-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0059_alter_element_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulateddatapoint',
            name='responseoption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulateddatapoints', to='sahel.responseoption'),
        ),
        migrations.AlterField(
            model_name='simulateddatapoint',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulateddatapoints', to='sahel.scenario'),
        ),
    ]
