# Generated by Django 3.2.14 on 2022-08-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0060_auto_20220817_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='kcal_per_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
