# Generated by Django 3.2.14 on 2022-08-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0061_element_kcal_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='output_variables',
            field=models.BooleanField(default=True),
        ),
    ]
