# Generated by Django 3.2.14 on 2022-09-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0065_alter_element_aggregate_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responseoption',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
