# Generated by Django 3.2.14 on 2022-09-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0066_auto_20220906_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Element',
            new_name='Variable',
        ),
    ]
