# Generated by Django 3.2.14 on 2022-09-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0067_rename_element_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
