# Generated by Django 3.2.14 on 2022-09-13 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0069_auto_20220913_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='situational_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='sahel.situationalanalysis'),
        ),
    ]
