# Generated by Django 3.2.14 on 2022-09-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0070_variable_situational_analysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TheoryOfChange',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='situational_analysis',
        ),
        migrations.DeleteModel(
            name='SituationalAnalysis',
        ),
    ]
