# Generated by Django 3.2.14 on 2022-09-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0072_element_situationalanalysis_theoryofchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='sahel.element'),
        ),
    ]
