# Generated by Django 3.2.14 on 2022-09-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0073_variable_element'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situationalanalysis',
            options={'verbose_name': 'Analyse de situation'},
        ),
    ]
