# Generated by Django 3.2.14 on 2022-09-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0075_alter_variable_element_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='element_group_integer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
