# Generated by Django 3.2.14 on 2022-09-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0076_element_element_group_integer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='element_group',
        ),
    ]
