# Generated by Django 3.2.14 on 2022-09-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0077_remove_variable_element_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='element_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='sahel.elementgroup'),
        ),
    ]
