# Generated by Django 3.2.14 on 2022-09-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0078_element_element_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='element_group_integer',
        ),
    ]
