# Generated by Django 3.2.14 on 2022-09-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0080_theoryofchange_toc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='situationalanalysis',
            name='element_type',
            field=models.CharField(choices=[('SA', 'Analyse de situation')], default='SA', max_length=2),
        ),
    ]
