# Generated by Django 3.2.14 on 2022-09-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0081_situationalanalysis_element_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theoryofchange',
            old_name='toc_type',
            new_name='element_type',
        ),
    ]
