# Generated by Django 3.2.14 on 2022-09-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0082_rename_toc_type_theoryofchange_element_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theoryofchange',
            options={'verbose_name': 'Théorie du changement'},
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['label']},
        ),
    ]
