# Generated by Django 3.2.14 on 2022-09-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0083_auto_20220914_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['label']},
        ),
    ]
