# Generated by Django 3.2.14 on 2022-09-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0084_alter_element_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='x_pos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='y_pos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
