# Generated by Django 3.2.14 on 2022-09-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0086_shockstructure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='from_variable',
            new_name='from_element',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='to_variable',
            new_name='to_element',
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('from_element', 'to_element')},
        ),
    ]
