# Generated by Django 3.2.14 on 2022-09-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0088_auto_20220915_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connection',
            new_name='VariableConnection',
        ),
    ]
