# Generated by Django 3.2.14 on 2022-09-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0089_rename_connection_variableconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('from_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_connections', to='sahel.element')),
                ('to_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_connections', to='sahel.element')),
            ],
            options={
                'ordering': ['-date_created'],
                'unique_together': {('from_element', 'to_element')},
            },
        ),
    ]
