# Generated by Django 3.2.14 on 2022-09-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0091_auto_20220920_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='situationalanalysis',
            name='trend',
            field=models.CharField(blank=True, choices=[('AA', 'Improving'), ('BB', 'Stagnant'), ('CC', 'Worsening')], max_length=2, null=True),
        ),
    ]
