# Generated by Django 3.2.14 on 2022-09-26 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0093_situationalanalysis_vulnerability'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariablePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.FloatField()),
                ('y_pos', models.FloatField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='sahel.story')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='sahel.variable')),
            ],
        ),
    ]
