# Generated by Django 3.2.15 on 2022-09-28 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0096_elementgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='samra_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sahel.samramodel'),
        ),
        migrations.AddField(
            model_name='elementgroup',
            name='samra_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sahel.samramodel'),
        ),
        migrations.AddField(
            model_name='variable',
            name='samra_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sahel.samramodel'),
        ),
    ]
