# Generated by Django 3.2.15 on 2022-09-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0098_source_samra_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseoption',
            name='samra_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responseoptions', to='sahel.samramodel'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='samra_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='sahel.samramodel'),
        ),
    ]
