# Generated by Django 3.2.15 on 2022-09-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0101_alter_story_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='elements',
            field=models.ManyToManyField(blank=True, related_name='stories', to='sahel.Element'),
        ),
    ]
