# Generated by Django 3.2.15 on 2022-09-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0102_alter_story_elements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='samra_model',
            new_name='samramodel',
        ),
        migrations.RenameField(
            model_name='elementgroup',
            old_name='samra_model',
            new_name='samramodel',
        ),
        migrations.RenameField(
            model_name='responseoption',
            old_name='samra_model',
            new_name='samramodel',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='samra_model',
            new_name='samramodel',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='samra_models',
            new_name='samramodels',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='samra_model',
            new_name='samramodel',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='samra_model',
            new_name='samramodel',
        ),
    ]
