# Generated by Django 3.2.15 on 2022-09-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0103_auto_20220928_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='samramodel',
            name='default_story',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaultfor', to='sahel.story'),
        ),
    ]
