# Generated by Django 3.2.15 on 2022-10-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0104_samramodel_default_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EvidenceBit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('eb_date', models.DateField(blank=True, null=True)),
                ('elements', models.ManyToManyField(blank=True, to='sahel.Element')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencebits', to='sahel.source')),
            ],
        ),
    ]
