# Generated by Django 3.2.15 on 2022-10-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0105_auto_20221005_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencebit',
            name='elements',
            field=models.ManyToManyField(blank=True, related_name='evidencebits', to='sahel.Element'),
        ),
    ]
