# Generated by Django 3.2.15 on 2022-10-06 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0106_alter_evidencebit_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableposition',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variablepositions', to='sahel.story'),
        ),
        migrations.AlterField(
            model_name='variableposition',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variablepositions', to='sahel.variable'),
        ),
        migrations.CreateModel(
            name='ElementPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.FloatField()),
                ('y_pos', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementpositions', to='sahel.element')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementpositions', to='sahel.story')),
            ],
        ),
    ]
