# Generated by Django 3.2.15 on 2022-10-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0107_auto_20221006_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('samramodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sahel.samramodel')),
            ],
        ),
    ]
