# Generated by Django 3.2.15 on 2022-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0108_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='elements', to='sahel.Sector'),
        ),
    ]
