# Generated by Django 3.2.15 on 2022-10-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0111_alter_elementposition_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variableposition',
            unique_together={('variable', 'story')},
        ),
    ]
