# Generated by Django 3.2.15 on 2022-10-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0113_auto_20221013_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samramodel',
            options={'verbose_name': 'SAMRA model'},
        ),
        migrations.AddField(
            model_name='elementconnection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theoryofchange',
            name='element_type',
            field=models.CharField(choices=[('IV', 'Intervention'), ('IC', 'Intervention Cluster'), ('SO', 'Sub-Outcome'), ('PO', 'Primary Outcome'), ('SG', 'Sector Goal'), ('PG', 'Programme Goal')], default='IV', max_length=2),
        ),
    ]
