# Generated by Django 3.2.15 on 2022-10-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0114_auto_20221013_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situationalanalysis',
            name='resilience',
        ),
        migrations.AddField(
            model_name='situationalanalysis',
            name='resilience_vulnerability',
            field=models.CharField(blank=True, choices=[('AA', 'High'), ('BB', 'Medium'), ('CC', 'Low')], max_length=2, null=True, verbose_name='resilience/vulnerability'),
        ),
    ]
