# Generated by Django 3.2.15 on 2022-10-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0117_alter_situationalanalysis_resilience_vulnerability'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='sahel.source'),
        ),
    ]
