# Generated by Django 3.2.15 on 2022-10-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0118_element_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='sector_type',
            field=models.CharField(blank=True, choices=[('FS', 'Formal'), ('IS', 'Informal')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('samramodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sahel.samramodel')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='elements', to='sahel.Region'),
        ),
    ]
