# Generated by Django 3.2.15 on 2022-10-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0119_auto_20221014_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='kumu_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
