# Generated by Django 3.2.15 on 2022-10-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0120_element_kumu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='sector_type',
            field=models.CharField(blank=True, choices=[('FS', 'Formal'), ('IS', 'Informal'), ('BS', 'Both')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='situationalanalysis',
            name='element_type',
            field=models.CharField(choices=[('SA', 'Situational Analysis')], default='SA', max_length=2),
        ),
    ]
