# Generated by Django 3.2.15 on 2022-10-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0121_auto_20221014_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='region',
            new_name='regions',
        ),
    ]
