# Generated by Django 3.2.15 on 2022-10-14 20:24

import colorfield.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0122_rename_region_element_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SAFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('color', colorfield.fields.ColorField(default='#696969', image_field=None, max_length=18, samples=None)),
                ('safield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safieldoptions', to='sahel.safield')),
            ],
        ),
        migrations.CreateModel(
            name='SAFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('sa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safieldvalues', to='sahel.situationalanalysis')),
                ('safieldoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safieldvalues', to='sahel.safieldoption')),
            ],
        ),
    ]
