# Generated by Django 3.2.15 on 2022-10-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0123_safield_safieldoption_safieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='safieldoption',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='safield',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
