# Generated by Django 3.2.15 on 2023-02-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0125_alter_safieldoption_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecasteddatapoint',
            name='admin0',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='measureddatapoint',
            name='admin0',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='simulateddatapoint',
            name='admin0',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
