# Generated by Django 3.2.15 on 2023-02-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0126_auto_20230226_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdconstantvalue',
            name='admin0',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='unit',
            field=models.CharField(blank=True, choices=[('tête', 'tête'), ('tête / mois', 'tête / mois'), ('tête / an', 'tête / an'), ('LCY', 'LCY'), ('LCY / mois', 'LCY / mois'), ('LCY / jour', 'LCY / jour'), ('LCY / an', 'LCY / an'), ('LCY / tête', 'LCY / tête'), ('LCY / kg', 'LCY / kg'), ('LCY / L', 'LCY / L'), ('kg', 'kg'), ('kg / mois', 'kg / mois'), ('kg / jour', 'kg / jour'), ('L', 'L'), ('L / mois', 'L / mois'), ('L / jour', 'L / jour'), ('kcal', 'kcal'), ('kcal / jour', 'kcal / jour'), ('1', '1'), ('personne', 'personne'), ('kcal / personne / jour', 'kcal / personne / jour'), ('1 / mois', '1 / mois'), ('1 / an', '1 / an'), ('mm / jour', 'mm / jour'), ('NDVI', 'NDVI'), ('USD / tonne', 'USD / tonne')], max_length=100, null=True),
        ),
    ]
