# Generated by Django 3.2.15 on 2023-02-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0127_auto_20230226_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='mrt_prixmarche_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
