# Generated by Django 3.2.15 on 2023-03-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0128_variable_mrt_prixmarche_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicConstantValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('admin0', models.CharField(blank=True, max_length=200, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countryconstantvalues', to='sahel.variable')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseConstantValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin0', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantvalues', to='sahel.variable')),
                ('responseoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantvalues', to='sahel.responseoption')),
            ],
        ),
        migrations.DeleteModel(
            name='ConstantValue',
        ),
    ]
