# Generated by Django 3.2.15 on 2023-03-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0129_auto_20230301_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsevalue',
            name='admin0',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responseconstantvalue',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responseconstantvalues', to='sahel.variable'),
        ),
        migrations.AlterField(
            model_name='responseconstantvalue',
            name='responseoption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responseconstantvalues', to='sahel.responseoption'),
        ),
    ]
