# Generated by Django 3.2.15 on 2023-03-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0130_auto_20230302_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='must_be_positive',
            field=models.BooleanField(default=True),
        ),
    ]
