# Generated by Django 3.2.15 on 2023-03-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0131_variable_must_be_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecasteddatapoint',
            name='lower_bound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecasteddatapoint',
            name='upper_bound',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
