# Generated by Django 3.2.15 on 2023-03-02 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0132_auto_20230302_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='stock_initial_value_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock', to='sahel.variable'),
        ),
    ]
