# Generated by Django 3.2.15 on 2023-03-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0133_variable_stock_initial_value_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='sd_type',
            field=models.CharField(blank=True, choices=[('Stock', 'Stock'), ('Flow', 'Flow'), ('Variable', 'Variable'), ('Input', 'Input'), ('Constant', 'Constant'), ('Seasonal Input', 'Entrée Saisonnière'), ('Pulse Input', 'Entrée Impulsion'), ('Household Constant', 'Qualité Ménage'), ('Scenario Constant', 'Variation Scénario'), ('Geographic Constant', 'Constant Géographique')], max_length=100, null=True),
        ),
    ]
