# Generated by Django 3.2.15 on 2023-03-03 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0134_alter_variable_sd_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='stock_initial_value_variable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock', to='sahel.variable'),
        ),
    ]
