# Generated by Django 3.2.15 on 2023-03-03 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0135_alter_variable_stock_initial_value_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='stock_initial_value_variable',
            field=models.OneToOneField(blank=True, limit_choices_to={'sd_type__in': ['Constant', 'Household Constant', 'Scenario Constant', 'Geographic Constant']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock', to='sahel.variable'),
        ),
    ]
