# Generated by Django 3.2.15 on 2023-03-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0136_alter_variable_stock_initial_value_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicconstantvalue',
            name='element',
            field=models.ForeignKey(limit_choices_to={'sd_type': 'Geographic Constant'}, on_delete=django.db.models.deletion.CASCADE, related_name='countryconstantvalues', to='sahel.variable'),
        ),
        migrations.AlterField(
            model_name='householdconstantvalue',
            name='element',
            field=models.ForeignKey(limit_choices_to={'sd_type': 'Household Constant'}, on_delete=django.db.models.deletion.CASCADE, related_name='householdconstantvalues', to='sahel.variable'),
        ),
        migrations.AlterField(
            model_name='measureddatapoint',
            name='element',
            field=models.ForeignKey(limit_choices_to={'sd_type': 'Input'}, on_delete=django.db.models.deletion.CASCADE, related_name='measureddatapoints', to='sahel.variable'),
        ),
        migrations.AlterField(
            model_name='pulsevalue',
            name='element',
            field=models.ForeignKey(limit_choices_to={'sd_type': 'Pulse Input'}, on_delete=django.db.models.deletion.CASCADE, related_name='pulsevalues', to='sahel.variable'),
        ),
        migrations.AlterField(
            model_name='responseconstantvalue',
            name='element',
            field=models.ForeignKey(limit_choices_to={'sd_type': 'Constant'}, on_delete=django.db.models.deletion.CASCADE, related_name='responseconstantvalues', to='sahel.variable'),
        ),
        migrations.AlterField(
            model_name='scenarioconstantvalue',
            name='element',
            field=models.ForeignKey(limit_choices_to={'sd_type': 'Scenario Constant'}, on_delete=django.db.models.deletion.CASCADE, related_name='scenarioconstantvalues', to='sahel.variable'),
        ),
        migrations.AlterField(
            model_name='seasonalinputdatapoint',
            name='element',
            field=models.ForeignKey(limit_choices_to={'sd_type': 'Seasonal Input'}, on_delete=django.db.models.deletion.CASCADE, related_name='seasonalinputdatapoints', to='sahel.variable'),
        ),
    ]
