# Generated by Django 3.2.15 on 2023-03-06 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0139_alter_variable_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='sd_sink',
            field=models.ForeignKey(blank=True, limit_choices_to={'sd_type': 'Stock'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inflows', to='sahel.variable'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='sd_source',
            field=models.ForeignKey(blank=True, limit_choices_to={'sd_type': 'Stock'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outflows', to='sahel.variable'),
        ),
    ]
