# Generated by Django 3.2.15 on 2023-03-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0140_auto_20230306_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalinputdatapoint',
            name='admin0',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seasonalinputdatapoint',
            name='admin1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seasonalinputdatapoint',
            name='admin2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
