# Generated by Django 3.2.15 on 2023-03-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0141_auto_20230306_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdconstantvalue',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='householdconstantvalues', to='sahel.source'),
        ),
    ]
