# Generated by Django 3.2.15 on 2023-03-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0145_alter_variable_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='element_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='sahel.elementgroup'),
        ),
    ]
