# Generated by Django 3.2.15 on 2023-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahel', '0146_variable_element_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsevalue',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
